---
- name: Check current RPM crypto policy
  command:
    cmd: update-crypto-policies --show
  changed_when: false
  register: current_rpm_policy

- name: "Set RPM crypto policy to {{ policy }}"
  command:
    cmd: "update-crypto-policies --set {{ policy | upper }}"
  when: current_rpm_policy.stdout != policy | upper
